apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-webapp
  labels: 
    app: employees
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      ServiceAccountName: clo835
      containers:
      - name: e-webapp
        image: 387584877503.dkr.ecr.us-east-1.amazonaws.com/finalproject-webapp
        env:
        - name: DBHOST 
          value: "e-mysql"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: root
        - name: DBPWD 
          value: db123
       - name: GROUP_NAME
         valueFrom:
           configMapKeyRef:
             name: webapp-config
             key: GROUP_NAME
       - name: IMAGE_URL
         valueFrom:
           configMapKeyRef:
             name: webapp-config
             key: IMAGE_URL
       ports: 
       - containerPort: 81
         protocol: TCP
          
