apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-webapp
  labels: 
    app: employees
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      ServiceAccountName: clo835
      containers:
      - name: e-webapp
        image: 387584877503.dkr.ecr.us-east-1.amazonaws.com/finalproject-webapp
        env:
      - name: DBHOST
        valueFrom:
          configMapKeyRef:
            name: webapp-config
            key: DBHOST
       - name: DBPORT
         valueFrom:
           configMapKeyRef:
             name: webapp-config
             key: DBPORT
       - name: DBUSER
         value: root
       - name: DBPWD 
         value: db123
       - name: GROUP_NAME
         valueFrom:
           configMapKeyRef:
             name: webapp-config
             key: GROUP_NAME
       - name: image
         valueFrom:
           configMapKeyRef:
             name: webapp-config
             key: image
             
       ports: 
       - containerPort: 81
         protocol: TCP
          
